SEED: 2023
output_dir: 'data/exprs_iros23_release/imap_single_transformer/trn.all-imap.3.pos.sgtype-rgb.rn50.clip-depth-layer.4-hidden.512-history.200-enc.concat-act.linear-attn.pos'
resume_file: null
resume_optimizer: null

train_batch_size: 32 #32
val_batch_size: 64
gradient_accumulation_steps: 1
num_epochs: 25
num_train_steps: null
warmup_steps: 2500
log_steps: 500
valid_steps: 2500

optim: 'adamw'
learning_rate: 3e-4
lr_sched: 'linear' # inverse_sqrt, linear
betas: [0.9, 0.98]
weight_decay: 0.01
grad_norm: 5
n_workers: 4
pin_mem: True

DATASET:
  dataset_class: 'NavDemoDataset'
  trn_scene_ids: '*' 
  # trn_scene_ids: ['gZ6f7yhEvPG']
  val_scene_ids: []
  rgb_image_dir: null
  semseg_dir: null
  rgb_ft_dir: 'data/datasets/objectnav/mp3d_70k_demos_prefts/rgb_fts/clip'
  depth_ft_dir: 'data/datasets/objectnav/mp3d_70k_demos_prefts/depth_fts'
  sem_ft_dir: 'data/datasets/objectnav/mp3d_70k_demos_prefts/sem_fts'
  meta_dir: 'data/datasets/objectnav/mp3d_70k_demos_prefts/meta_infos_lmdb'
  num_ft_views: 1
  rgb_image_size: 224
  max_steps: 500
  num_history_fts: 200
  inflection_weight: 3.477512060914205
  stop_weight: null
  use_thda: True
  # max_episode_steps: 2000

  gpscompass_noise_type: null # null, zero, gaussian

  infer_visual_feature_task: True # False
  max_future_step_size: 20
  infer_depth_feature: False

  infer_local_map_task: False
  map_types: ['obs', 'exp'] # ['obs', 'exp']
  map_image_size: 240
  map_image_max_pool: 5
  # map_dir: 'data/datasets/objectnav/mp3d_70k_demo_maps_48m_nocld'
  map_dir: null

MODEL:
  model_class: 'NavImapSingleTransformer'
  action_clf_class: 'linear' # linear, ClsPrediction
  encoder_type: 'concat' # concat, concat_linear, add
  encoder_add_objgoal: True
  hidden_size: 512
  num_actions: 6  # stop, move forward, turn left, turn right, look up, look down

  obj_embed_file: null

  dropout_rate: 0.1

  infer_visual_feature_loss: 0.
  infer_depth_feature: False
  infer_visual_feature_loss_type: 'nce' # mse, nce

  infer_local_map_loss: 0.
  pred_map_input_token_dim: 64
  pred_map_image_size: 48
  pred_map_nchannels: 2
  infer_local_map_loss_type: 'clf' # mse, clf
  
  infer_sem_label_loss: 0. #1

  USE_SEMANTICS: False
  USE_PRED_SEMANTICS: False
  SWITCH_TO_PRED_SEMANTICS_UPDATE: 0
  embed_sge: False
  SEMANTIC_ENCODER:
    rednet_ckpt: "data/rednet-models/rednet_semmap_mp3d_tuned.pth"
    cnn_type: "ResnetSemSegEncoder"
    output_size: 256
    backbone: "resnet18"
    train_encoder: True
    embedding_size: 4
    is_thda: True
    num_classes: 29

  DEPTH_ENCODER:
    cnn_type: "VlnResnetDepthEncoder" # VlnResnetDepthEncoder, None
    output_size: 128 #128
    backbone: "resnet50"
    trainable: False
    ddppo_checkpoint: "data/ddppo-models/gibson-2plus-resnet50.pth"

  RGB_ENCODER:
    cnn_type: "resnet50_clip"  # ResnetRGBEncoder, resnet50_clip, resnet50_imagenet, resnet18_imagenet, None
    output_size: 256 #256
    # specific configuration for ResnetRGBEncoder
    backbone: "resnet50"
    train_encoder: False
    normalize_visual_inputs: False # specific for ResnetRGBEncoder

  SEM_FT_ENCODER:
    type: null # null, linear
    input_size: 22
    output_size: 128

  USE_GPS: True
  USE_COMPASS: True
  SEQ2SEQ:
    use_prev_action: True

  STATE_ENCODER:
    rnn_type: "transformer"
    num_hidden_layers: 4
    num_attention_heads: 8
    learnable_step_embedding: False
    max_steps: 500
    add_pos_attn: True #False

    hidden_act: "gelu"
    dropout_prob: 0.1
    intermediate_size: 2048 #3072
    layer_norm_eps: 1e-12

  MAP_ENCODER:
    imap_size: 3
    token_embed_type: 'single' # single, multi (different token embedding for each token), null
    encode_position: True
